[settings]
source_dir = /storage/emulated/0/Download/netease/cloudmusic/Music/
target_dir = /storage/emulated/0/Music/
embed_metadata = true
threads = 2
decode_threads = 8
log_file = music_converter.log
log_level = INFO
use_ncmdump = false
